name: iOS Build

on:
  push:
    branches: [ main, minversfix ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate bundle
      run: npx bare-pack --target ios --linked --out app/app.bundle.mjs backend/backend.mjs
    
    - name: Setup Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod --version
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
    
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace autopassmobileexample.xcworkspace \
          -scheme autopassmobileexample \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -derivedDataPath build \
          build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/build/Build/Products/Release-iphonesimulator/*.app
        retention-days: 7